"""empty message

Revision ID: 48271611cea6
Revises: 60f765d63850
Create Date: 2023-01-11 15:25:58.994636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48271611cea6'
down_revision = '60f765d63850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.Column('expereince', sa.String(length=10), nullable=True),
    sa.Column('expiredDate', sa.DateTime(), nullable=False),
    sa.Column('applied_user', sa.Integer(), nullable=True),
    sa.Column('posted_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applied_user'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['posted_user'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
