"""empty message

Revision ID: 7502581889ad
Revises: 71e837ea784a
Create Date: 2023-01-06 21:28:13.329878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7502581889ad'
down_revision = '71e837ea784a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephon', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('telephon')

    # ### end Alembic commands ###
