"""empty message

Revision ID: 8072f8ee8cc7
Revises: f76c28fd053f
Create Date: 2023-01-08 10:55:33.315541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8072f8ee8cc7'
down_revision = 'f76c28fd053f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=345), nullable=False),
    sa.Column('phone', sa.String(length=22), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=9), nullable=False),
    sa.Column('city', sa.String(length=12), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('github_link', sa.Text(), nullable=True),
    sa.Column('linkedin_link', sa.Text(), nullable=True),
    sa.Column('fileName', sa.String(length=50), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('cv_name', sa.String(length=12), nullable=True),
    sa.Column('cv', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'employee', ['owner'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('owner')

    op.drop_table('employee')
    # ### end Alembic commands ###
