"""empty message

Revision ID: bf61e03be9e5
Revises: b4c902963f91
Create Date: 2023-01-08 11:51:10.025089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf61e03be9e5'
down_revision = 'b4c902963f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=9), nullable=False),
    sa.Column('city', sa.String(length=12), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('fileName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fileName', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    op.drop_table('company')
    # ### end Alembic commands ###
